### ISSUE TITLE
Error revisar codigo de lista

### ISSUE THREAD

**Issue by BryanJT01** [AdrianGonzalezB/OpusList#2]
El recuadro de "no existe sale constantemente" esto debido a que lo muestra dentro del for.

Para arreglarlo es recomendable usar un boolean en el for que revise si existe o no el codigo en la lista, entonces se mostrara el panel correspondiente
![image](https://user-images.githubusercontent.com/77690759/141209036-766303c8-d143-4788-8cf3-136a195e8196.png)

**Comment by AngelLlompart** [comment]
What is stated in this issue is an error on the update from the menu

**Comment by AdrianGonzalezB** [comment]
Fixed and committed.
