### ISSUE TITLE
Error when canceling the image load on insert.

### ISSUE THREAD

**Issue by AngelLlompart** [AdrianGonzalezB/OpusList#3]
![image](https://user-images.githubusercontent.com/77398966/141338222-f326c245-ef0f-4230-b620-accde4415201.png)

Fix it swapping the String, you can not put the file into the String if there is nothing selected:
![image](https://user-images.githubusercontent.com/77398966/141338580-39d466ed-7fbf-43d3-aea6-87f5d934593e.png)
![image](https://user-images.githubusercontent.com/77398966/141338597-3cc350a6-4cb4-4623-88dc-4500ebf18878.png)

**Comment by AngelLlompart** [comment]
The same happens on the update.

**Comment by AdrianGonzalezB** [comment]
Fixed. 
Now when you don't choose a file it no longer gives an error in the insert or the update
