### ISSUE TITLE
When double clicking, registre should not be editable.

### ISSUE THREAD

**Issue by AngelLlompart** [AdrianGonzalezB/OpusList#4]
When trying to change the registre, it actually updates and it should not.
![image](https://user-images.githubusercontent.com/77398966/141341026-7844f2fe-b8ab-4885-959b-6d81c3b168bc.png)
![image](https://user-images.githubusercontent.com/77398966/141341050-203e9ab4-3341-44a0-8f12-36ada2ae6b24.png)

**Comment by AdrianGonzalezB** [comment]
It is not a bug, but I'll implement that option.

**Comment by AdrianGonzalezB** [comment]
Added.
